genernal:
  label: 基本设置
  items:
    index_notice:
      name: index_notice
      label: 首页描述
      type: textarea
      default: '我看到那些岁月如何奔驰，挨过了冬季，便迎来了春天。——梭罗《瓦尔登湖》' 
    aWord_enabled:
      name:  aWord_enabled
      label: 一言
      type: radio
      data-type: bool
      default: false
      description: '是否开启一言，开启后，首页描述为一言，默认为关闭'
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    aWordType:
      name: aWordType
      label: 一言类型
      type: select
      default: 'd'
      options:
        - value: 'a'
          label: 'a 动画'
        - value: 'b'
          label: 'b 漫画'
        - value: 'c'
          label: 'c 游戏'
        - value: 'd'
          label: 'd 文学'
        - value: 'e'
          label: 'e 原创'
        - value: 'f'
          label: 'f 来自网络'
        - value: 'g'
          label: 'g 其他'
        - value: 'h'
          label: 'h 影视'
        - value: 'i'
          label: 'i 诗词'
        - value: 'j'
          label: 'j 网易云'
        - value: 'k'
          label: 'k 哲学'
        - value: 'l'
          label: 'l 抖机灵'
    aWordTypes:
      name: aWordTypes
      label: 一言类型多种组合（开启后，上面单类型将失效）
      type: text
      placeholder: '如：a,b'
      description: '上面代号a,b分别表示，动画：a，漫画：b，其他代号请参考此网站：https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0'
    aWordNum:
      name: aWordNum
      label: 一言最少字数
      type: text
      placeholder: '默认10个'
    avatarLogo:
      name: avatarLogo
      label: 头像
      type: attachment   
    # music:
    #   name: music
    #   label: 音乐（为空不显示图标）
    #   type: textarea
    #   placeholder: '歌曲链接1#*#歌曲名称,歌曲链接2#*#歌曲名称'
    github:
      name: github               
      label: github              
      type: text                
      placeholder: 'github个人主页链接'       
    email:
      name: email               
      label: 邮箱              
      type: text                
      placeholder: '个人邮箱'      
    record:
      name: record
      label: ICP备案号
      type: text
      placeholder: '填写ICP备案号'
    record2img:
      name: record2img               
      label: 备案图标          
      type: attachment               
      placeholder: '公安备案图标地址（修改默认）'            
    record2:
      name: record2
      label: 公安备案号
      type: text
      placeholder: '填写公安备案号'


style:
  label: 样式设置
  items:
    mdui_theme:
      name: mdui_theme
      label: 主题色
      type: select
      default: 'mdui-theme-primary-blue'
      options:
        - value: 'mdui-theme-primary-blue'
          label: '宝石蓝'
        - value: 'mdui-theme-primary-green'
          label: '清新绿'
        - value: 'mdui-theme-primary-red'
          label: '姨妈红'
        - value: 'mdui-theme-primary-pink'
          label: '少女粉'
        - value: 'mdui-theme-primary-purple'
          label: '基佬紫'
        - value: 'mdui-theme-primary-orange'
          label: '大橘观'
        - value: 'mdui-theme-primary-blue-grey'
          label: '萧条灰'
        - value: 'mdui-theme-primary-brown'
          label: '低调棕'
        - value: 'mdui-theme-primary-cyan'
          label: '靛蓝青'
    dark_enabled:
      name: dark_enabled
      label: 黑暗模式
      type: radio
      data-type: bool
      default: false
      description: '是否开启黑暗模式，默认为 false'
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    drawer_enabled:
      name: drawer_enabled
      label: 抽屉状态
      type: radio
      data-type: bool
      default: false
      description: '是否开启展开状态？默认隐藏'
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    indeximg:
      name: indeximg               
      label: 镇站图              
      type: attachment               
      placeholder: '图片地址'                       
    drawimg:
      name: drawimg               
      label: 抽屉图              
      type: attachment               
      placeholder: '图片地址'                
    mdui_icons:
      name: mdui_icons
      label: 字体图标样式
      type: select
      default: 'Material Icons Outlined'
      description: '推荐使用Material Icons Outlined'
      options:
        - value: 'Material Icons'
          label: 'Material Icons'
        - value: 'Material Icons Outlined'
          label: 'Material Icons Outlined' 
    code_css:
      name: code_css
      label: 代码样式
      type: select
      default: 'default'
      data-type: string
      options:
        - value: "agate"
          label: "agate"
        - value: "androidstudio"
          label: "androidstudio"
        - value: "atom-one-dark"
          label: "atom-one-dark"
        - value: "default"
          label: "default"
        - value: "github"
          label: "github"
        - value: "github-dark"
          label: "github-dark"
        - value: "gradient-dark"
          label: "gradient-dark"
        - value: "gradient-light"
          label: "gradient-light"
        - value: "nord"
          label: "nord"
        - value: "/base16/nova"
          label: "nova"
        - value: "paraiso-light"
          label: "paraiso-light"
        - value: "/base16/material"
          label: "material"
    comment_js:
      name: comment_js               
      label: 评论组件JS              
      type: text                
      placeholder: '填入外部评论组件URL'              
      description: '导入外部评论组件JS,推荐默认评论组件以完美支持黑暗模式' 