genernal:
  label: 基本设置
  items:
    index_notice:
      name: index_notice
      label: 首页公告
      type: textarea
      default: '不以物喜不以己悲' 
    profile_desc:
      name: profile_desc               
      label: 侧边栏个人信息卡片描述              
      type: text                
      placeholder: '一些描述...'     
    music:
      name: music
      label: 音乐（为空不显示图标）
      type: textarea
      placeholder: '歌曲链接1#*#歌曲名称,歌曲链接2#*#歌曲名称'
    github:
      name: github               
      label: github              
      type: text                
      placeholder: 'github个人主页链接'       
    email:
      name: email               
      label: 邮箱              
      type: text                
      placeholder: '个人邮箱'      
    record:
      name: record
      label: 备案号
      type: text
      placeholder: '填写备案号'


style:
  label: 样式设置
  items:
    mdui_theme:
      name: mdui_theme
      label: 主题色
      type: select
      default: 'mdui-theme-primary-blue'
      options:
        - value: 'mdui-theme-primary-blue'
          label: '宝石蓝'
        - value: 'mdui-theme-primary-green'
          label: '原谅绿'
        - value: 'mdui-theme-primary-red'
          label: '姨妈红'
        - value: 'mdui-theme-primary-pink'
          label: '少女粉'
        - value: 'mdui-theme-primary-purple'
          label: '基佬紫'
        - value: 'mdui-theme-primary-orange'
          label: '大橘观'
        - value: 'mdui-theme-primary-blue-grey'
          label: '萧条灰'
        - value: 'mdui-theme-primary-brown'
          label: '低调棕'
        - value: 'mdui-theme-primary-cyan'
          label: '靛蓝青'
    indeximg:
      name: indeximg               
      label: 镇站图              
      type: attachment               
      placeholder: '图片地址'           
      default: ''               
    drawimg:
      name: drawimg               
      label: 抽屉图              
      type: attachment               
      placeholder: '图片地址'           
      default: ''     
    mdui_icons:
      name: mdui_icons
      label: 字体图标样式
      type: select
      default: 'MI'
      options:
        - value: 'MI'
          label: 'Material-Icons'
        - value: 'MIO'
          label: 'Material Icons Outlined' 
    code_css:
      name: code_css
      label: 代码样式
      type: select
      default: 'default'
      data-type: string
      options:
        - value: "agate"
          label: "agate"
        - value: "androidstudio"
          label: "androidstudio"
        - value: "atom-one-dark"
          label: "atom-one-dark"
        - value: "default"
          label: "default"
        - value: "github"
          label: "github"
        - value: "github-dark"
          label: "github-dark"
        - value: "gradient-dark"
          label: "gradient-dark"
        - value: "gradient-light"
          label: "gradient-light"
        - value: "nord"
          label: "nord"
        - value: "/base16/nova"
          label: "nova"
        - value: "paraiso-light"
          label: "paraiso-light"
        - value: "/base16/material"
          label: "material"
    comment_style:
      name: comment_style
      label: 评论模块样式
      type: select
      default: '样式1'
      data-type: string
      options:
        - value: "comment1"
          label: "样式1"
        - value: "comment2"
          label: "样式2"
        
others:
  label: 其他
  items:
    ad_enabled:
      name: ad_enabled
      label: 侧边栏广告
      type: radio
      data-type: bool
      default: false
      description: '是否开启侧边栏广告，默认为 false'
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    adimg:
      name: adimg               
      label: 广告图片              
      type: attachment               
      placeholder: '图片地址'           
      default: ''               
    adlink:
      name: adlink
      label: 广告链接
      type: text
      placeholder: '填写广告链接'